/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedExitRouteImport } from './routes/_authenticated/exit'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedHolidaysRouteImport } from './routes/_authenticated/holidays'
import { Route as AuthenticatedLeaveBalancesRouteImport } from './routes/_authenticated/leave-balances'
import { Route as AuthenticatedLeavesRouteImport } from './routes/_authenticated/leaves'
import { Route as AuthenticatedOrgChartRouteImport } from './routes/_authenticated/org-chart'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedPayrollPayslipsRouteImport } from './routes/_authenticated/payroll/payslips'
import { Route as AuthenticatedPayrollRunsRouteImport } from './routes/_authenticated/payroll/runs'
import { Route as AuthenticatedPayrollSalaryStructuresRouteImport } from './routes/_authenticated/payroll/salary-structures'
import { Route as AuthenticatedPerformanceAppraisalsRouteImport } from './routes/_authenticated/performance/appraisals'
import { Route as AuthenticatedPerformanceGoalsRouteImport } from './routes/_authenticated/performance/goals'
import { Route as AuthenticatedRecruitmentApplicationsRouteImport } from './routes/_authenticated/recruitment/applications'
import { Route as AuthenticatedRecruitmentJobsRouteImport } from './routes/_authenticated/recruitment/jobs'
import { Route as AuthenticatedTrainingCoursesRouteImport } from './routes/_authenticated/training/courses'
import { Route as AuthenticatedTrainingEnrollmentsRouteImport } from './routes/_authenticated/training/enrollments'
import { Route as AuthenticatedTravelIndexRouteImport } from './routes/_authenticated/travel/index'
import { Route as AuthenticatedTravelExpensesRouteImport } from './routes/_authenticated/travel/expenses'
import { Route as AuthenticatedTravelTicketsRouteImport } from './routes/_authenticated/travel/tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExitRoute = AuthenticatedExitRouteImport.update({
  id: '/exit',
  path: '/exit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHolidaysRoute = AuthenticatedHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaveBalancesRoute =
  AuthenticatedLeaveBalancesRouteImport.update({
    id: '/leave-balances',
    path: '/leave-balances',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeavesRoute = AuthenticatedLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgChartRoute = AuthenticatedOrgChartRouteImport.update({
  id: '/org-chart',
  path: '/org-chart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollPayslipsRoute =
  AuthenticatedPayrollPayslipsRouteImport.update({
    id: '/payroll/payslips',
    path: '/payroll/payslips',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayrollRunsRoute =
  AuthenticatedPayrollRunsRouteImport.update({
    id: '/payroll/runs',
    path: '/payroll/runs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayrollSalaryStructuresRoute =
  AuthenticatedPayrollSalaryStructuresRouteImport.update({
    id: '/payroll/salary-structures',
    path: '/payroll/salary-structures',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerformanceAppraisalsRoute =
  AuthenticatedPerformanceAppraisalsRouteImport.update({
    id: '/performance/appraisals',
    path: '/performance/appraisals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerformanceGoalsRoute =
  AuthenticatedPerformanceGoalsRouteImport.update({
    id: '/performance/goals',
    path: '/performance/goals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruitmentApplicationsRoute =
  AuthenticatedRecruitmentApplicationsRouteImport.update({
    id: '/recruitment/applications',
    path: '/recruitment/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruitmentJobsRoute =
  AuthenticatedRecruitmentJobsRouteImport.update({
    id: '/recruitment/jobs',
    path: '/recruitment/jobs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainingCoursesRoute =
  AuthenticatedTrainingCoursesRouteImport.update({
    id: '/training/courses',
    path: '/training/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainingEnrollmentsRoute =
  AuthenticatedTrainingEnrollmentsRouteImport.update({
    id: '/training/enrollments',
    path: '/training/enrollments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTravelIndexRoute =
  AuthenticatedTravelIndexRouteImport.update({
    id: '/travel/',
    path: '/travel/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTravelExpensesRoute =
  AuthenticatedTravelExpensesRouteImport.update({
    id: '/travel/expenses',
    path: '/travel/expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTravelTicketsRoute =
  AuthenticatedTravelTicketsRouteImport.update({
    id: '/travel/tickets',
    path: '/travel/tickets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/exit': typeof AuthenticatedExitRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/holidays': typeof AuthenticatedHolidaysRoute
  '/leave-balances': typeof AuthenticatedLeaveBalancesRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/org-chart': typeof AuthenticatedOrgChartRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/payroll/payslips': typeof AuthenticatedPayrollPayslipsRoute
  '/payroll/runs': typeof AuthenticatedPayrollRunsRoute
  '/payroll/salary-structures': typeof AuthenticatedPayrollSalaryStructuresRoute
  '/performance/appraisals': typeof AuthenticatedPerformanceAppraisalsRoute
  '/performance/goals': typeof AuthenticatedPerformanceGoalsRoute
  '/recruitment/applications': typeof AuthenticatedRecruitmentApplicationsRoute
  '/recruitment/jobs': typeof AuthenticatedRecruitmentJobsRoute
  '/training/courses': typeof AuthenticatedTrainingCoursesRoute
  '/training/enrollments': typeof AuthenticatedTrainingEnrollmentsRoute
  '/travel/expenses': typeof AuthenticatedTravelExpensesRoute
  '/travel/tickets': typeof AuthenticatedTravelTicketsRoute
  '/travel/': typeof AuthenticatedTravelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/exit': typeof AuthenticatedExitRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/holidays': typeof AuthenticatedHolidaysRoute
  '/leave-balances': typeof AuthenticatedLeaveBalancesRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/org-chart': typeof AuthenticatedOrgChartRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/payroll/payslips': typeof AuthenticatedPayrollPayslipsRoute
  '/payroll/runs': typeof AuthenticatedPayrollRunsRoute
  '/payroll/salary-structures': typeof AuthenticatedPayrollSalaryStructuresRoute
  '/performance/appraisals': typeof AuthenticatedPerformanceAppraisalsRoute
  '/performance/goals': typeof AuthenticatedPerformanceGoalsRoute
  '/recruitment/applications': typeof AuthenticatedRecruitmentApplicationsRoute
  '/recruitment/jobs': typeof AuthenticatedRecruitmentJobsRoute
  '/training/courses': typeof AuthenticatedTrainingCoursesRoute
  '/training/enrollments': typeof AuthenticatedTrainingEnrollmentsRoute
  '/travel/expenses': typeof AuthenticatedTravelExpensesRoute
  '/travel/tickets': typeof AuthenticatedTravelTicketsRoute
  '/travel': typeof AuthenticatedTravelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/exit': typeof AuthenticatedExitRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/holidays': typeof AuthenticatedHolidaysRoute
  '/_authenticated/leave-balances': typeof AuthenticatedLeaveBalancesRoute
  '/_authenticated/leaves': typeof AuthenticatedLeavesRoute
  '/_authenticated/org-chart': typeof AuthenticatedOrgChartRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/_authenticated/payroll/payslips': typeof AuthenticatedPayrollPayslipsRoute
  '/_authenticated/payroll/runs': typeof AuthenticatedPayrollRunsRoute
  '/_authenticated/payroll/salary-structures': typeof AuthenticatedPayrollSalaryStructuresRoute
  '/_authenticated/performance/appraisals': typeof AuthenticatedPerformanceAppraisalsRoute
  '/_authenticated/performance/goals': typeof AuthenticatedPerformanceGoalsRoute
  '/_authenticated/recruitment/applications': typeof AuthenticatedRecruitmentApplicationsRoute
  '/_authenticated/recruitment/jobs': typeof AuthenticatedRecruitmentJobsRoute
  '/_authenticated/training/courses': typeof AuthenticatedTrainingCoursesRoute
  '/_authenticated/training/enrollments': typeof AuthenticatedTrainingEnrollmentsRoute
  '/_authenticated/travel/expenses': typeof AuthenticatedTravelExpensesRoute
  '/_authenticated/travel/tickets': typeof AuthenticatedTravelTicketsRoute
  '/_authenticated/travel/': typeof AuthenticatedTravelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/announcements'
    | '/assets'
    | '/attendance'
    | '/dashboard'
    | '/departments'
    | '/documents'
    | '/employees'
    | '/exit'
    | '/expenses'
    | '/holidays'
    | '/leave-balances'
    | '/leaves'
    | '/org-chart'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/shifts'
    | '/payroll/payslips'
    | '/payroll/runs'
    | '/payroll/salary-structures'
    | '/performance/appraisals'
    | '/performance/goals'
    | '/recruitment/applications'
    | '/recruitment/jobs'
    | '/training/courses'
    | '/training/enrollments'
    | '/travel/expenses'
    | '/travel/tickets'
    | '/travel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/announcements'
    | '/assets'
    | '/attendance'
    | '/dashboard'
    | '/departments'
    | '/documents'
    | '/employees'
    | '/exit'
    | '/expenses'
    | '/holidays'
    | '/leave-balances'
    | '/leaves'
    | '/org-chart'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/shifts'
    | '/payroll/payslips'
    | '/payroll/runs'
    | '/payroll/salary-structures'
    | '/performance/appraisals'
    | '/performance/goals'
    | '/recruitment/applications'
    | '/recruitment/jobs'
    | '/training/courses'
    | '/training/enrollments'
    | '/travel/expenses'
    | '/travel/tickets'
    | '/travel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/announcements'
    | '/_authenticated/assets'
    | '/_authenticated/attendance'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/documents'
    | '/_authenticated/employees'
    | '/_authenticated/exit'
    | '/_authenticated/expenses'
    | '/_authenticated/holidays'
    | '/_authenticated/leave-balances'
    | '/_authenticated/leaves'
    | '/_authenticated/org-chart'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/shifts'
    | '/_authenticated/payroll/payslips'
    | '/_authenticated/payroll/runs'
    | '/_authenticated/payroll/salary-structures'
    | '/_authenticated/performance/appraisals'
    | '/_authenticated/performance/goals'
    | '/_authenticated/recruitment/applications'
    | '/_authenticated/recruitment/jobs'
    | '/_authenticated/training/courses'
    | '/_authenticated/training/enrollments'
    | '/_authenticated/travel/expenses'
    | '/_authenticated/travel/tickets'
    | '/_authenticated/travel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exit': {
      id: '/_authenticated/exit'
      path: '/exit'
      fullPath: '/exit'
      preLoaderRoute: typeof AuthenticatedExitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/holidays': {
      id: '/_authenticated/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof AuthenticatedHolidaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave-balances': {
      id: '/_authenticated/leave-balances'
      path: '/leave-balances'
      fullPath: '/leave-balances'
      preLoaderRoute: typeof AuthenticatedLeaveBalancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaves': {
      id: '/_authenticated/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof AuthenticatedLeavesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org-chart': {
      id: '/_authenticated/org-chart'
      path: '/org-chart'
      fullPath: '/org-chart'
      preLoaderRoute: typeof AuthenticatedOrgChartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll/payslips': {
      id: '/_authenticated/payroll/payslips'
      path: '/payroll/payslips'
      fullPath: '/payroll/payslips'
      preLoaderRoute: typeof AuthenticatedPayrollPayslipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll/runs': {
      id: '/_authenticated/payroll/runs'
      path: '/payroll/runs'
      fullPath: '/payroll/runs'
      preLoaderRoute: typeof AuthenticatedPayrollRunsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll/salary-structures': {
      id: '/_authenticated/payroll/salary-structures'
      path: '/payroll/salary-structures'
      fullPath: '/payroll/salary-structures'
      preLoaderRoute: typeof AuthenticatedPayrollSalaryStructuresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance/appraisals': {
      id: '/_authenticated/performance/appraisals'
      path: '/performance/appraisals'
      fullPath: '/performance/appraisals'
      preLoaderRoute: typeof AuthenticatedPerformanceAppraisalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance/goals': {
      id: '/_authenticated/performance/goals'
      path: '/performance/goals'
      fullPath: '/performance/goals'
      preLoaderRoute: typeof AuthenticatedPerformanceGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruitment/applications': {
      id: '/_authenticated/recruitment/applications'
      path: '/recruitment/applications'
      fullPath: '/recruitment/applications'
      preLoaderRoute: typeof AuthenticatedRecruitmentApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruitment/jobs': {
      id: '/_authenticated/recruitment/jobs'
      path: '/recruitment/jobs'
      fullPath: '/recruitment/jobs'
      preLoaderRoute: typeof AuthenticatedRecruitmentJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training/courses': {
      id: '/_authenticated/training/courses'
      path: '/training/courses'
      fullPath: '/training/courses'
      preLoaderRoute: typeof AuthenticatedTrainingCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training/enrollments': {
      id: '/_authenticated/training/enrollments'
      path: '/training/enrollments'
      fullPath: '/training/enrollments'
      preLoaderRoute: typeof AuthenticatedTrainingEnrollmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/travel/': {
      id: '/_authenticated/travel/'
      path: '/travel'
      fullPath: '/travel/'
      preLoaderRoute: typeof AuthenticatedTravelIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/travel/expenses': {
      id: '/_authenticated/travel/expenses'
      path: '/travel/expenses'
      fullPath: '/travel/expenses'
      preLoaderRoute: typeof AuthenticatedTravelExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/travel/tickets': {
      id: '/_authenticated/travel/tickets'
      path: '/travel/tickets'
      fullPath: '/travel/tickets'
      preLoaderRoute: typeof AuthenticatedTravelTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedExitRoute: typeof AuthenticatedExitRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedHolidaysRoute: typeof AuthenticatedHolidaysRoute
  AuthenticatedLeaveBalancesRoute: typeof AuthenticatedLeaveBalancesRoute
  AuthenticatedLeavesRoute: typeof AuthenticatedLeavesRoute
  AuthenticatedOrgChartRoute: typeof AuthenticatedOrgChartRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
  AuthenticatedPayrollPayslipsRoute: typeof AuthenticatedPayrollPayslipsRoute
  AuthenticatedPayrollRunsRoute: typeof AuthenticatedPayrollRunsRoute
  AuthenticatedPayrollSalaryStructuresRoute: typeof AuthenticatedPayrollSalaryStructuresRoute
  AuthenticatedPerformanceAppraisalsRoute: typeof AuthenticatedPerformanceAppraisalsRoute
  AuthenticatedPerformanceGoalsRoute: typeof AuthenticatedPerformanceGoalsRoute
  AuthenticatedRecruitmentApplicationsRoute: typeof AuthenticatedRecruitmentApplicationsRoute
  AuthenticatedRecruitmentJobsRoute: typeof AuthenticatedRecruitmentJobsRoute
  AuthenticatedTrainingCoursesRoute: typeof AuthenticatedTrainingCoursesRoute
  AuthenticatedTrainingEnrollmentsRoute: typeof AuthenticatedTrainingEnrollmentsRoute
  AuthenticatedTravelExpensesRoute: typeof AuthenticatedTravelExpensesRoute
  AuthenticatedTravelTicketsRoute: typeof AuthenticatedTravelTicketsRoute
  AuthenticatedTravelIndexRoute: typeof AuthenticatedTravelIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedExitRoute: AuthenticatedExitRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedHolidaysRoute: AuthenticatedHolidaysRoute,
  AuthenticatedLeaveBalancesRoute: AuthenticatedLeaveBalancesRoute,
  AuthenticatedLeavesRoute: AuthenticatedLeavesRoute,
  AuthenticatedOrgChartRoute: AuthenticatedOrgChartRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
  AuthenticatedPayrollPayslipsRoute: AuthenticatedPayrollPayslipsRoute,
  AuthenticatedPayrollRunsRoute: AuthenticatedPayrollRunsRoute,
  AuthenticatedPayrollSalaryStructuresRoute:
    AuthenticatedPayrollSalaryStructuresRoute,
  AuthenticatedPerformanceAppraisalsRoute:
    AuthenticatedPerformanceAppraisalsRoute,
  AuthenticatedPerformanceGoalsRoute: AuthenticatedPerformanceGoalsRoute,
  AuthenticatedRecruitmentApplicationsRoute:
    AuthenticatedRecruitmentApplicationsRoute,
  AuthenticatedRecruitmentJobsRoute: AuthenticatedRecruitmentJobsRoute,
  AuthenticatedTrainingCoursesRoute: AuthenticatedTrainingCoursesRoute,
  AuthenticatedTrainingEnrollmentsRoute: AuthenticatedTrainingEnrollmentsRoute,
  AuthenticatedTravelExpensesRoute: AuthenticatedTravelExpensesRoute,
  AuthenticatedTravelTicketsRoute: AuthenticatedTravelTicketsRoute,
  AuthenticatedTravelIndexRoute: AuthenticatedTravelIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
